package com.project.model;

// Generated 4 Feb, 2016 3:08:19 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details", catalog = "awsmaven_db")
public class UserDetails implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String userName;
	private String email;
	private String password;
	private Set<UserDetailsAngBook> userDetailsAngBooks = new HashSet<UserDetailsAngBook>(
			0);

	public UserDetails() {
	}

	public UserDetails(String firstName, String userName, String email,
			String password) {
		this.firstName = firstName;
		this.userName = userName;
		this.email = email;
		this.password = password;
	}

	public UserDetails(String firstName, String userName, String email,
			String password, Set<UserDetailsAngBook> userDetailsAngBooks) {
		this.firstName = firstName;
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.userDetailsAngBooks = userDetailsAngBooks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "first_name", nullable = false, length = 2000)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "user_name", nullable = false, length = 2000)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "email", nullable = false, length = 2000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 2000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<UserDetailsAngBook> getUserDetailsAngBooks() {
		return this.userDetailsAngBooks;
	}

	public void setUserDetailsAngBooks(
			Set<UserDetailsAngBook> userDetailsAngBooks) {
		this.userDetailsAngBooks = userDetailsAngBooks;
	}

}
