package com.project.model;

// Generated 4 Feb, 2016 3:08:19 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserDetailsAngBook generated by hbm2java
 */
@Entity
@Table(name = "user_details_ang_book", catalog = "awsmaven_db")
public class UserDetailsAngBook implements java.io.Serializable {

	private Integer id;
	private AngBook angBook;
	private UserDetails userDetails;

	public UserDetailsAngBook() {
	}

	public UserDetailsAngBook(AngBook angBook, UserDetails userDetails) {
		this.angBook = angBook;
		this.userDetails = userDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ang_book_id", nullable = false)
	public AngBook getAngBook() {
		return this.angBook;
	}

	public void setAngBook(AngBook angBook) {
		this.angBook = angBook;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_details_id", nullable = false)
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

}
