package com.project.model;

// Generated 26 Mar, 2016 2:28:40 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "awsmaven_db")
public class User implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String userName;
	private String email;
	private String password;
	private boolean active;
	private UserRole userRoles;
	private Set<UserAngBook> userAngBooks = new HashSet<UserAngBook>(0);

	public User() {
	}

	public User(String firstName, String userName, String email,
			String password, boolean active) {
		this.firstName = firstName;
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.active = active;
	}

	public User(String firstName, String userName, String email,
			String password, boolean active, UserRole userRoles,
			Set<UserAngBook> userAngBooks) {
		this.firstName = firstName;
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.active = active;
		this.userRoles = userRoles;
		this.userAngBooks = userAngBooks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "first_name", nullable = false, length = 2000)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "user_name", nullable = false, length = 2000)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "email", nullable = false, length = 2000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 2000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public UserRole getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(UserRole userRoles) {
		this.userRoles = userRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserAngBook> getUserAngBooks() {
		return this.userAngBooks;
	}

	public void setUserAngBooks(Set<UserAngBook> userAngBooks) {
		this.userAngBooks = userAngBooks;
	}

}
